name       : kio-extras
version    : 17.08.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.2/src/kio-extras-17.08.2.tar.xz : d6fc25a3f83750ca2af27768a7278314139bda8591df70b8f49b3d11379a74dd
license    : GPL-2.0
component  : desktop.kde
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libmtp)
    - pkgconfig(libssh)
    - pkgconfig(phonon4qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - gperf
    - karchive-devel
    - kbookmarks-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kguiaddons-devel
    - khtml-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpty-devel
    - shared-mime-info
    - solid-devel
setup      : |
    # Fix smb stuff with 4.7
    %patch -p1 < $pkgfiles/a36b797913a844dbb26d5dc1542b3ce304f5f445.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
