name       : kio-extras
version    : 22.08.3
release    : 98
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kio-extras-22.08.3.tar.xz : 2836c9417044c4aba8594b7b355edf55aa686c5c40cfde7bf1e4f118843a73eb
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
optimize   : lto
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libssh)
    - pkgconfig(libmtp)
    - pkgconfig(phonon4qt5)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - gperf
    - kactivities-devel
    - kactivities-stats-devel
    - karchive-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kdsoap-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
