name       : kio-extras
version    : 17.08.1
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kio-extras-17.08.1.tar.xz : 15550ee9869abee53c0cc77a67e1675f22696ccde9352dfbc62de4bc954f60c2
license    : GPL-2.0
component  : desktop.kde
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libmtp)
    - pkgconfig(libssh)
    - pkgconfig(phonon4qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - gperf
    - karchive-devel
    - kbookmarks-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kguiaddons-devel
    - khtml-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpty-devel
    - shared-mime-info
    - solid-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
