name       : kio-extras
version    : 20.08.2
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.2/src/kio-extras-20.08.2.tar.xz : 9d4b9cb5a4002ad2127c5c5c4d25ff95d53de32ea08348e8dc40fe83d950076e
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libmtp)
    - pkgconfig(libssh)
    - pkgconfig(phonon4qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - extra-cmake-modules
    - gperf
    - karchive-devel
    - kbookmarks-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kdsoap-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpty-devel
    - kwindowsystem-devel
    - shared-mime-info
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
