name       : kio-extras
version    : 18.08.1
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kio-extras-18.08.1.tar.xz : dc3f185908c05e02c555f36b7ef182e6a935b990e28d71f835c5e051d842060f
license    : GPL-2.0
component  : desktop.kde
optimize   : lto
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libmtp)
    - pkgconfig(libssh)
    - pkgconfig(phonon4qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - gperf
    - karchive-devel
    - kbookmarks-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kguiaddons-devel
    - khtml-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpty-devel
    - shared-mime-info
    - solid-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
