name       : kio-extras
version    : 20.12.3
release    : 73
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kio-extras-20.12.3.tar.xz : ba5b90dbbc08ce1a0aeb456e3bba89a328538a41950e7bfa3e04f24b7f6741e2
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
optimize   : lto
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libssh)
    - pkgconfig(libmtp)
    - pkgconfig(phonon4qt5)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - gperf
    - kactivities-devel
    - kactivities-stats-devel
    - karchive-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kdsoap-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
