name       : kio-extras
version    : 21.12.0
release    : 89
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kio-extras-21.12.0.tar.xz : 246234481d7a8ad4047b46cd7dde6b3eb4a7507122a0eb6df73893749ad19c96
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
optimize   : lto
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libssh)
    - pkgconfig(libmtp)
    - pkgconfig(phonon4qt5)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - gperf
    - kactivities-devel
    - kactivities-stats-devel
    - karchive-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kdsoap-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
