name       : kio-extras
version    : 19.08.2
release    : 44
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kio-extras-19.08.2.tar.xz : a0b8f08ab8f9d36cfdc950470f75726e90e9fba159bc2035931cfa6efbfe4394
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libmtp)
    - pkgconfig(libssh)
    - pkgconfig(phonon4qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - gperf
    - karchive-devel
    - kbookmarks-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kguiaddons-devel
    - khtml-devel
    - kiconthemes-devel
    - kio-devel
    - kpty-devel
    - shared-mime-info
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
