name       : kio-extras
version    : 21.04.3
release    : 80
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kio-extras-21.04.3.tar.xz : 4af9f8a10e0c16006d97cf63439f91c05a04533ec6ee2ec0223dbfcc1d39d62d
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
optimize   : lto
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(libssh)
    - pkgconfig(libmtp)
    - pkgconfig(phonon4qt5)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - gperf
    - kactivities-devel
    - kactivities-stats-devel
    - karchive-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kdsoap-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
