name       : kio-extras
version    : 20.12.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kio-extras-20.12.0.tar.xz : 530a9643009647d6b8e8e799b4018ce5d06a687c918f53af6652dbfa7fe3ab29
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libmtp)
    - pkgconfig(libssh)
    - pkgconfig(phonon4qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - extra-cmake-modules
    - gperf
    - karchive-devel
    - kbookmarks-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kdsoap-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kwindowsystem-devel
    - shared-mime-info
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
        -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
