name       : kio-extras
version    : 19.12.1
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kio-extras-19.12.1.tar.xz : 79b3735510c3c8da9b3e019ee5a54b115f85bb8d89f1c04dbbf16dde3007e7b6
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
optimize   : lto
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(libmtp)
    - pkgconfig(libssh)
    - pkgconfig(phonon4qt5)
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - gperf
    - karchive-devel
    - kbookmarks-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kpty-devel
    - shared-mime-info
    - syntax-highlighting-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
